### ISSUE TITLE
Fatal error: undefined function bw_as_array

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-block#27]
When using the Distributor plugin I noticed a message in the Editor Selection meta box.

Fatal error: Uncaught Error: Call to undefined function bw_as_array() in 
C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\class-oik-block-editor-opinions.php:281 

Note: The oik plugin was not active at the time. 

Stack trace: #0 C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\class-oik-block-editor-opinions.php(264): oik_block_editor_opinions->report_header() #1 C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\class-oik-block-post-subcommands.php(60): oik_block_editor_opinions->report() #2 C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\oik-block-opinions.php(127): oik_block_post_subcommands->consider('1468') #3 C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\oik-block-meta-box.php(50): oik_block_opinions_subcommand('consider', 'post', '1468') #4 C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\oik-block-meta-box.php(21): oik_block_display_post_opinions(Object(WP_Post)) #5 C:\apache\htdocs\wp-admin\includes\template.php(1073): oik_block_meta_box(Object(WP_Post), Array) #6 C:\apache\htdocs\wp-admin\ in C:\apache\htdocs\wordpress\wp-content\plugins\oik-block\admin\class-oik-block-editor-opinions.php on line 281

**Comment by bobbingwide** [comment]
I got this again on s.b/wp50-beta5 when I deactivated oik but left oik-block active. This time I got the WSOD.

**Comment by bobbingwide** [comment]
The logic which loads files should first test for the existence of the file. 
But bw_as_array may come from oik or oik-bwtrace. So we can't use it to determine that oik has been loaded.  It would be better to test for did_action( 'oik_admin_loaded' );
